name: data-science

channels:
  - conda-forge
  - defaults

dependencies:
  - beautifulsoup4>=4.9.3
  - bokeh>=2.3.0
  - chart-studio>=1.1.0
  - geopy>=2.1.0
  - ipympl>=0.7.0
  - ipywidgets>=7.6
  - keras>=2.4.3
  - nltk>=3.5
  - patsy>=0.5.1
  - plotly>=4.14.3
  - pillow>=8.1.2
  - pygeohash>=1.2.0
  - pytesseract>=0.3.7
  - python-tlsh>=4.2.1
  - scikit-image>=0.18.1
  - scikit-learn>=0.24.1
  - scipy>=1.6.2
  - sqlalchemy
  - statsmodels>=0.12.2
  - seaborn>=0.11.1
  - tensorflow>=2.4.1
  - wordcloud>=1.8.1
